spring:
  aop:
    proxy-target-class: false
  freemarker:
    template-loader-path: classpath:/static/
    cache: false
    suffix: .html
  servlet:
    multipart:
      max-file-size:  -1
      max-request-size: -1
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/education
    username: root
    password: weiyanan
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wei.eduyang.domain  # 注意：对应实体类的路径
server:
  port: 8081
  session:
    timeout: 86400000
logging:
  path: /root/log/service.log

app:
  uploadDir:
    /root/upload/
  uploadMaxSizeTip: 30M
  uploadMaxSize:  31457280

